name: CI

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run the test suite
      run: bash $GITHUB_WORKSPACE/unittest.sh
